version: 2.1

jobs:
  run_unit_tests:
    description: Run unit tests
    docker:
      - image: cimg/base:2024.05
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t luczwanenbergg/001-dockerize-nodejs:$TAG . --target=test
  publish_docker_image:
    docker:
      - image: cimg/base:2024.05
    steps:
      - checkout
      - run: echo "hello world"

workflows:
  test:
    jobs:
      - run_unit_tests
  publish:
    jobs:
      - run_unit_tests:
          filters:
            tags:
              only: /^v.*/
      - publish_docker_image:
          filters:
            tags:
              only: /^v.*/
        requires:
          - run_unit_tests
